FROM python:3.13.3-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY src/ /app/src/
COPY requirements/ /app/requirements/
COPY scripts/entrypoint.sh /app/scripts/entrypoint.sh
RUN chmod +x /app/scripts/entrypoint.sh && \
    ls -l /app/src/scripts/  # برای دیباگ

RUN pip install --no-cache-dir -r /app/requirements/dev.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]